apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: vehicle-api-vehicle-db
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: vehicle-api
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: vehicle-api
spec:
  name: vehicle-db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: vehicle-db
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: vehicle-api

