apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: hello-nodejs.demo.apps.ik.am.20230509071436.0.0
spec:
  refName: hello-nodejs.demo.apps.ik.am
  version: 20230509071436.0.0
  releaseNotes: |
    Release v20230509071436.0.0 of package hello-nodejs.demo.apps.ik.am
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/making/workloads/hello-nodejs-demo-bundle@sha256:1caade19f27848ea0d29c4665fdcf66df8ce96f2853cd274d4f1708190fa4425
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

