apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  labels:
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hello
    spec:
      containers:
      - image: ghcr.io/making/hello-demo@sha256:7daa4778eeb6f630b593099ec1b080dd9a3d99a0d6377489f118ef26ada8bbe0
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

