apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hello
    spec:
      containers:
      - image: ghcr.io/making/supply-chain/hello-demo@sha256:1ebe9f9d13353bf2c95545ba32c381a376a5f99104a132eac1bcf52ad45c43ef
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

